# Üretimde mutlaka değiştirin / ExternalSecrets / SealedSecrets ile yönetin.
apiVersion: v1
kind: Secret
metadata:
  name: beebak-secrets
  namespace: beebak
type: Opaque
stringData:
  postgresPassword: "11051994"
  rabbitUser: "beebak"
  rabbitPassword: "beebak"
  connectionString: "Host=postgres;Port=5432;Database=BeeBAK;Username=postgres;Password=11051994"
  redisConfig: "redis:6379"
